[project]
name = "database-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Giancarlo Lester", email = "gian.lepear@gmail.com" }
]
requires-python = ">=3.12.10"
dependencies = [
    "pre-commit>=4.2.0",
]

[project.scripts]
database-ai = "database_ai:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "ruff>=0.11.13",
]

[tool.ruff]
line-length = 140
extend-exclude = [ "**/migrations", ".ruff_cache", ".venv", "alembic/versions/**", "pyproject.toml" ]
lint.extend-select = [
  "B",   # flake8-bugbear
  "E",   # pycodestyle
  "F",   # Pyflakes
  "FA",
  "I",
  "S",
  "SIM", # flake8-simplify
  "UP",  # pyupgrade
  "W",
]
lint.ignore = [ "F401" ]

[tool.pyproject-fmt]
column_width = 120
indent = 2
keep_full_version = false
max_supported_python = "3.12.10"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
asyncio_default_test_loop_scope = "function"
testpaths = [ "tests" ]
env_files = [ ".env.test" ]
addopts = "--cov=src --cov-report term --cov-report html:htmlcov"

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
]
omit = [ "*/__init__.py" ]

[tool.mypy]
plugins = [ "pydantic.mypy" ]
disable_error_code = [
  "import-untyped",
  "no-redef",
  "var-annotated",
  "assignment",
]
